### ISSUE TITLE
[BUG] when I load in the sky is permanently black it is not night on my world

### ISSUE THREAD

**Issue by yefffernuts** [QuestCraftPlusPlus/QuestCraft#156]

**Comment by ATXLtheAxolotl** [comment]
No description is provided nor anyway to reproduce the problem.

**Comment by Nathannaters** [comment]
I think I have the same problem, I'm using the quest 1 and the sky doesnt seem to load in. I can always see stars but they too look weird. It might be because of render distance plus every block and entity that goes above the horizon/rendered blocks will have a bright outline like its an ESP cheat in games. (Idk if this will help find the cause but I hope it does, I'd really love to see the sky lol)

**Comment by WaffleDevsAlt** [comment]
You have to turn your graphics to fabulous. It an issue with the shaders
