### ISSUE TITLE
[BUG] game infinitly loads when i have mods downloaded.

### ISSUE THREAD

**Issue by William-06** [QuestCraftPlusPlus/QuestCraft#161]
I downloaded a few mods that were recomended, but when i try to luanch the game it just infinitly loads with the three dots. I have tried everything from reinstaling the intire game to redownloading the mods. But i still just see three dots when trying to luanch the game.

**Comment by mmdgamer** [comment]
Same issue I think? It’s #160 right before yours

**Comment by joemama0912** [comment]
Try restarting your quest or allocating more ram

**Comment by mgamingpro** [comment]
Hi, I had the same issue. Turns out lithium completely breaks questcraft and causes infinite loading, you have to reinstall questcraft completely  in order to fix it as deleting it doesn’t do anything for some reason. It’s latest update broke it, not sure why the devs still have it listed as compatible and one of the recommended mods 💀

**Comment by sdpixl** [comment]
Lithium works completely fine. You have had some sort of user error while installing, @joemama0912, please refer to our new fix in our discord server in #common-issues, hopefully it can help.

**Comment by mmdgamer** [comment]
@sdpixl no lithium is actually broken you probably have version 0.7.7 and it works but version 0.7.8 makes the game load forever

**Comment by mmdgamer** [comment]
If anyone wants to download lithium then download version 0.7.7
