### ISSUE TITLE
[BUG] Weird colored noise on some frames

### ISSUE THREAD

**Issue by CyorgGit** [QuestCraftPlusPlus/QuestCraft#303]
**Describe the bug**
Occasionally, when walking around a world or even just standing still, sometimes for a brief period of time, the screen has a pink and yellow sort of noise, like a white noise from a TV.

**To Reproduce**
One of the ways to reproduce the behavior:
1. Make a new world
2. Walk around or stay still
3. It should happen.

**Screenshots**

https://user-images.githubusercontent.com/85780097/165410505-be3a9ef4-e6ca-4b45-80f8-ede60798d653.mp4

![vlcsnap-2022-04-26-18h47m10s065](https://user-images.githubusercontent.com/85780097/165410521-566c4a17-2eb8-4357-956f-2054adcf2a5f.png)

**Headset Details (please complete the following information):**
 - Quest Build: v39
 - Device: Quest 1
 - QuestCraft Version: 1.2.0

**Additional context**
The video and image are from when I was on v37, but even on v38 and v39 it still occurred.
It can also sometimes happen in worlds that have existed for a long time, not just new ones.
Doesn't happen when moving a lot, but sometimes happens when staying in the same few chunks for a while.

**Comment by StormDragon-64** [comment]
I have quest 2 and have never experienced this, so maybe it is quest 1 only bug

**Comment by kwmc-lucas** [comment]
@StormDragon-64 I think you're right, all of the other reports mention using Quest 1s.

Yes, I'm new to QuestCraft so 1.3.0 is the first and only version I've used.

**Comment by gusbunce** [comment]
Hey, sorry for the delay in a response! We are all very busy people. However, if you would like some more thorough support please reach out on the [discord](discord.gg/questcraft). We hope we can be of assistance :))

**Comment by kwmc-lucas** [comment]
I was having this issue too, using a Quest 1, but updating to the 1.3.1 Hotfix seems to have fixed it for me.

I think this may be due to using a different renderer, so please note that if you install 1.3.1, do not change the renderer as was the practice in previous versions.

My method:
Install the 1.3. .apk downloaded from GitHub (I found issues with the version available on SideQuest)
Open the App
Login to your account
Restart the Quest
Open the App
Change the loader to the one that begins with "fabric-loader-"
Play - it will download everything, show loading dots and then should go red, the game will start shortly after it goes red
