### ISSUE TITLE
[BUG] when i open the game it goes to the red screen for 3-5 sec and then crashes

### ISSUE THREAD

**Issue by arkaura** [QuestCraftPlusPlus/QuestCraft#45]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by JD-The-65th** [comment]
Please actually fill out the issue template, or else the devs will not be able to help.

Also, check to make sure you're using the third renderer, and update QC.

**Comment by tubtub1080** [comment]
Describe the bug
The game is no longer able to be redownloaded or seen after being redownloaded once uninstalled once

To Reproduce
Steps to reproduce the behavior:

Go to unknown sources 
Click on uninstall game
See error
Expected behavior
I expected that I could simply reinstall the game and once again see the application and use it



Headset Details (please complete the following information):

Quest Build: [e.g. v37.0]
Device: Quest_2]
QuestCraft Version [e.g. v1.0.0
Additional context
Once the game loaded I wasnt shown a menu and unable to play, so I uninstalled the game to hopefully reinstall it and play again, but once reinstalled I was unable to even see the game in unknown sources let alone play it

**Comment by Firepal** [comment]
@tubtub1080 Please create a new issue for the bug you are experiencing.
