### ISSUE TITLE
[FEATURE] Xaero's Minimap and Xaero's Wordmap compatibility. 

### ISSUE THREAD

**Issue by Eyndjl** [QuestCraftPlusPlus/QuestCraft#469]
**Is your feature request related to a problem? Please describe.**
For some unknown reason, instead of the world map, just a black background is displayed. The labels of mobs and players are present, waypoints too, but do not see the world map itself.
Moreover, the problem is relevant to both Xaero's Minimap and Xaero's Wordmap. 

**Describe the solution you'd like**
Solve the problem on the QuestCraft side or do a fork of Xaero's Minimap/Worldmap mods where this problem will be solved.

**Comment by TecEash1** [comment]
This problem *may* be fixed in QuestCraft v4.0 
For now I would recommend using Voxel map, we are sure that it works. The correct versions are below:
[1.18.2](https://cdn.modrinth.com/data/wkzK5379/versions/SDVTG1wT/voxelmap-1.18.2-1.11.2.jar)  | [1.19.3](https://cdn.modrinth.com/data/wkzK5379/versions/YGYMnNRA/voxelmap-1.19.3-1.12.0.jar)

**Comment by Merith-TK** [comment]
I tried using Xaeros on QuestCraft in the past, however the problem I ran into was accessing the map, also factor in there is an rendering issue for "on screen" waypoints that Xaeros itself detects `vivecraft` and disables because of

**Comment by Eyndjl** [comment]
Fixed in 4.0
