### ISSUE TITLE
[BUG] Not being able to log in (Login Failure)

### ISSUE THREAD

**Issue by fnfiseasy** [QuestCraftPlusPlus/QuestCraft#511]
### 🤔 Current Behavior

My game won't let me log in, pressing Microsoft Login and then doing the instructions, It just says a login failure has happened and it tells me to accept all the requirements and then press it again. I do have Minecraft on my account but it seems like

**Comment by DED0026** [comment]
**!DED's updated tutorial on the login issue:**

its been a while since there was an update/FAQ post on the login issue but here's another,
requirements for login issue:

1. you own minecraft java
2. you have a minecraft java username
**check both with this link:** 
https://www.minecraft.net/en-us/msaprofile/mygames/editprofile
3. your account is overage and can access this link: 
https://account.xbox.com/Settings

if it isn't though, there are extra steps you need to go through to log into QuestCraft:
you must add your account to a Microsoft family.

first you must have a overage account to start a Microsoft family.
1. log into this link with the overage account:
https://account.microsoft.com/family/home?refd=login.live.com
2. add your main account as a member.
3. accept invite you received in your main account's email.


**honorable mentions:**
the Xbox link must bring to a **interface with a bunch of options** to be checked off as a met requirement.
the overage account doesn't have to own java **but can**.
the main account has to be added to the family **as a member** instead of as an organizer.
the main account has to be added to the overage accounts family, **not the other way around**.
you **cannot invite yourself** as a member to a Microsoft family.

**ᵗʰᵃⁿᵏˢ ᵗᵒ ᵃˡˡ ᵗʰᵉ ᵖᵉᵒᵖˡᵉ ʷʰᵒ ᵗᵉˢᵗᵉᵈ ʷᶦᵗʰ ᵐᵉ**

**Comment by DED0026** [comment]
also it might be more convenient to come to our [discord server](https://discord.gg/questcraft) for assistance.

**Comment by fnfiseasy** [comment]
This tutorial for the login issue doesn't seem to work, i am over 18 and yet it still says "Login failure! Ensure you have acccepted the permission then try again. Click the Microsoft button again once done"

**Comment by fnfiseasy** [comment]
uninstalling using custom adb commands and installing again worked 👍
