### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lowill232** [QuestCraftPlusPlus/QuestCraft#54]
When I launch it and scroll down installations fabric does not pop up the list ends at 1.0 Please Fix.

**Comment by Firepal** [comment]
You might've forgot or incorrectly transferred the zip file's contents to the headset as instructed on the release page. 
The files **must** be already extracted somewhere on your computer, otherwise Windows will silently refuse to merge the files.

Reinstalling the launcher and transferring the files before running it for the first time may also help, but that's just what I did, so IDK.
