### ISSUE TITLE
[BUG] This very specific server does not load

### ISSUE THREAD

**Issue by SuperDZ555** [QuestCraftPlusPlus/QuestCraft#551]
### 🤔 Current Behavior

I tried to log into a server called DiamondFire (server ip is mcdiamondfire.com) and it says "Can't connect to server" and when I try to join it it says "Failed to connect to the server" with the details just being "Connection refused". This server has not shut down, and I can join it completely fine on my PC. On top of that, I tried to log into Hypixel, and it worked, but I also tried to log into this random server I found that had like 24 players on it and THAT worked, too. So it's just DiamondFire, and I don't know why. Any other server loads fine, details, icon, etc.; but DiamondFire SPECIFICALLY does not load anything.

### 🥽 Headset Details

Quest Build: v57
Device: Quest 2
Questcraft Version: The latest one, v4.0.2

**Comment by swaggio7** [comment]
Some servers are a bit finicky when it comes to playing on the Quest. You might need to include the port in the IP (mcdiamondfire.com:<port number>) or you might need the direct IP to the server (123.456.789, this is an example) in order to connect to it.
P.S: Some servers' anti-cheats may accidentally flag you and might kick (worst case, ban) you. Do your research on what server you're gonna join on QuestCraft. 
P.S.S: We also have a list of recommended servers in our [Discord.](https://discord.com/channels/820767484042018829/946021441298649158/1121556722021048432)

**Comment by 5ghzx** [comment]
If you only check two servers, is that enough for scientific evidence?

**Comment by thejudge156** [comment]
No, but I *have* tried others, and they typically work fine. I would need to look into this further.
