### ISSUE TITLE
Infinite loading screen and inability to turn on keep me logged in[BUG]

### ISSUE THREAD

**Issue by CatMaster8232** [QuestCraftPlusPlus/QuestCraft#71]
I was trying this out when on my first attempt it would just not load. I tried uninstalling and reinstalling and this time it has red and loads, then crashes to the log in screen. On a random attempt, it didn't crash me but went back to loading. I think this is due to be not being able to be always logged in but the way that the microsoft log in works, I can't use the stay logged in, even with the choose account button. I saw that the stay logged in is vital, so I need help fixing this.

**Comment by The-Blue-Goose** [comment]
it won't keep you logged in for some reason, however, you can get past the loading screen by restarting your headset and pressing the "Existing Account" Button rather than the other login (your account should show up if you logged in previously). Clicking play will still cause the game to load on a black screen for about a minute, but it should eventually load.
