### ISSUE TITLE
[BUG] Game launches once, but crashes repeatedly, and then loads infinitely. Attempting to change memory amount also breaks the entire game.

### ISSUE THREAD

**Issue by MissHotHeartness** [QuestCraftPlusPlus/QuestCraft#81]
So, after waking up and seeing the game STILL LOADING several hours after I fell asleep, I gave up, nearly threw the headset against the wall, and concluded that the game is COMPLETELY broken.

Steps to reproduce what happened:
1. Set up QuestCraft as the tutorials say, select third renderer, and launch the game.
2. Game immediately crashes or if I'm lucky, I make it ingame.
3. Attempt to launch again after that and it loads forever. Going outside the guardian at ALL or even getting close to the edge makes the game load infinitely as well, and even rarely crashes the whole client, including QuestCraft and PojavLauncher itself.

Expected behavior:
I expected the game to launch and go to the main menu with the QuestCraft logo and title world, but instead it never does except for when I completely delete every trace of the game and reinstall, and even then when I launch a 2nd time it does all the issues stated.

Headset Details:
 - Device: Quest 2
 - QuestCraft Version: 1.1.1

Game Details:
 - Version: 1.18.1 with Fabric
 - Mods: Only the 5 preinstalled ones

///

Also, am I allowed to maybe appeal my discord ban from SylveticHearts#2002 so I can get help with this? I said one joke yesterday, got muted permanently I think, then I went ballistic like an idiot and in short, got banned less than 5 minutes after joining the discord server which is a little extreme. I get I was asking for it, but whoever muted me wasn't helping to begin with.

Hopefully this extra question don't get banned from QuestCraft GitHub as well.

**Comment by artdeell** [comment]
Instead of throwing your headset against the wall and/or committing other atrocities to your headset, you can send the latestlog.txt from your last launch with the bug present. The file is located in `Android/data/net.kdt.pojavlaunch(.debug)/files/latestlog.txt`  on your headset's internal storage.
This may help the developers with investigating your issue, and making a fix for it.
Do note that `latestlog.txt` is different from Minecraft's own `latest.log`, as it contains way more useful debugging information.
